@echo off
echo ========================================
echo   PulseMate Backend - Starting...
echo ========================================
cd backend
echo [1/3] Installing dependencies...
call npm install
echo [2/3] Generating Prisma client...
call npx prisma generate
echo [3/3] Starting server on port 5000...
call npm run dev
